version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16.2
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  bot_and_api:
    container_name: bot_and_api
    build: .
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata: